/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import conexao.resultado;
import conexao.spacenet;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.banco;
import modelo.periodos;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
/**
 *
 * @author marco.junior
 */
public class FormPerm extends javax.swing.JFrame {

    private final resultado DAO;
    private final resultado DAO1;

    private spacenet con;
    
    public FormPerm() throws Exception {
        initComponents();
         DAO = new resultado();
         DAO1 = new resultado();
         desativaPeriodo();
         selectBanco();
         diretorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtPeriodo1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtPeriodo2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtPeriodo_1_Ini = new javax.swing.JTextField();
        jtPeriodo_1_Fim = new javax.swing.JTextField();
        jtPeriodo_3_Ini = new javax.swing.JTextField();
        jtPeriodo_2_Fim = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtPeriodo_2_Ini = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtPeriodo_4_Ini = new javax.swing.JTextField();
        jtPeriodo_6_Ini = new javax.swing.JTextField();
        jtPeriodo_5_Ini = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtPeriodo_7_Ini = new javax.swing.JTextField();
        jtPeriodo_9_Ini = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jtPeriodo_4_Fim = new javax.swing.JTextField();
        jtPeriodo_6_Fim = new javax.swing.JTextField();
        jtPeriodo_5_Fim = new javax.swing.JTextField();
        jtPeriodo_7_Fim = new javax.swing.JTextField();
        jtPeriodo_9_Fim = new javax.swing.JTextField();
        jtPeriodo_8_Fim = new javax.swing.JTextField();
        jtPeriodo_3_Fim = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jtPeriodo9 = new javax.swing.JTextField();
        jtPeriodo4 = new javax.swing.JTextField();
        jtPeriodo6 = new javax.swing.JTextField();
        jtPeriodo5 = new javax.swing.JTextField();
        jtPeriodo7 = new javax.swing.JTextField();
        jtPeriodo8 = new javax.swing.JTextField();
        jtPeriodo3 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jtPeriodo_8_Ini = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jtPeriodo10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jComboBoxBanco = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jcSelecaoPeriodo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtDayChange = new javax.swing.JFormattedTextField();
        jtDataInicio = new javax.swing.JFormattedTextField();
        jtDataFim = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PERMANENCIA - NEPOS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("1º PERÍODO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jtPeriodo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 80, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("PESQUISAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("RELATÓRIO DE PERMANÊNCIA - NEPOS -");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("INICIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("FIM");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("QUANTIDADE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("2º PERÍODO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jtPeriodo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("INICIO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("FIM");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jtPeriodo_1_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_1_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 76, -1));

        jtPeriodo_1_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPeriodo_1_Fim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPeriodo_1_FimActionPerformed(evt);
            }
        });
        getContentPane().add(jtPeriodo_1_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 80, -1));

        jtPeriodo_3_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_3_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 76, -1));

        jtPeriodo_2_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_2_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 80, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("3º PERÍODO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("4º PERÍODO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("5º PERÍODO");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("7º PERÍODO");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("6º PERÍODO");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("8º PERÍODO");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("9º PERÍODO");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jtPeriodo_2_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_2_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 76, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("INICIO");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jtPeriodo_4_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_4_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 76, -1));

        jtPeriodo_6_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_6_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 76, -1));

        jtPeriodo_5_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_5_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 76, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("INICIO");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("INICIO");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("INICIO");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        jtPeriodo_7_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_7_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 76, -1));

        jtPeriodo_9_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_9_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 76, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("INICIO");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("INICIO");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("INICIO");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jtPeriodo_4_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_4_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 80, -1));

        jtPeriodo_6_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_6_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 80, -1));

        jtPeriodo_5_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_5_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 80, -1));

        jtPeriodo_7_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_7_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 80, -1));

        jtPeriodo_9_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_9_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 80, -1));

        jtPeriodo_8_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_8_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 80, -1));

        jtPeriodo_3_Fim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_3_Fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 80, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("FIM");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("FIM");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("FIM");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("FIM");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("FIM");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("FIM");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setText("FIM");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, -1));

        jtPeriodo9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 80, -1));

        jtPeriodo4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 80, -1));

        jtPeriodo6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 80, -1));

        jtPeriodo5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 80, -1));

        jtPeriodo7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 80, -1));

        jtPeriodo8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 80, -1));

        jtPeriodo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 80, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 570, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 570, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 570, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 570, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 570, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 570, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 570, -1));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 570, -1));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 570, -1));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 570, -1));

        jtPeriodo_8_Ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo_8_Ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 76, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel35.setText("TOTAL");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, -1, -1));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 570, -1));

        jtPeriodo10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtPeriodo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 80, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setText("RELATÓRIO REALIZA CALCULO DE PERMANENCIA COM AS INFORMAÇÕES TRANSACIONAIS");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jComboBoxBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboBoxBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBancoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 140, -1));

        jButton3.setText("CONECTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 110, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Selecionar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 110, -1));

        jcSelecaoPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jcSelecaoPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 65, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("       SELECIONAR O PERIODO     ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setText("SELECIONAR BANCO DE DADOS");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("PERÍODO DE PERMANÊNCIA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("DAY CHANGE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("DATA PESQUISA INICIO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("DATA PESQUISA FIM");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        try {
            jtDayChange.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDayChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtDayChange.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtDayChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 102, -1));

        try {
            jtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDataInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtDataInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 102, -1));

        try {
            jtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtDataFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtDataFim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 102, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 630));

        jMenu1.setText("Configuração");

        jMenuItem1.setText("Periodos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatorios");

        jMenuItem4.setText("Periodos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem2.setText("Permanência");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String periodozero = jtPeriodo_1_Ini.getText();
        String periodo_1_final = jtPeriodo_1_Fim.getText();
        String periodo_2_inicio = jtPeriodo_2_Ini.getText();
        String periodo_2_final = jtPeriodo_2_Fim.getText();
        String periodo_3_inicio = jtPeriodo_3_Ini.getText();
        String periodo_3_final = jtPeriodo_3_Fim.getText();
        String periodo_4_inicio = jtPeriodo_4_Ini.getText();
        String periodo_4_final = jtPeriodo_4_Fim.getText();
        String periodo_5_inicio = jtPeriodo_5_Ini.getText();
        String periodo_5_final = jtPeriodo_5_Fim.getText();
        String periodo_6_inicio = jtPeriodo_6_Ini.getText();
        String periodo_6_final = jtPeriodo_6_Fim.getText();
        String periodo_7_inicio = jtPeriodo_7_Ini.getText();
        String periodo_7_final = jtPeriodo_7_Fim.getText();
        String periodo_8_inicio = jtPeriodo_8_Ini.getText();
        String periodo_8_final = jtPeriodo_8_Fim.getText();
        String periodo_9_inicio = jtPeriodo_9_Ini.getText();
        String periodo_9_final = jtPeriodo_9_Fim.getText();
        String bancoPermanencia = (String) jComboBoxBanco.getSelectedItem(); 
        
        
        String tipoPermanencia =  (String) jcSelecaoPeriodo.getSelectedItem();
        String dataperiodoInicio = jtDataInicio.getText();
        String[] dataperiodoInicioConversao = dataperiodoInicio.split("-");
        LocalDate converteinicio = LocalDate.of(Integer.parseInt(dataperiodoInicioConversao[2]),Integer.parseInt(dataperiodoInicioConversao[1]),Integer.parseInt(dataperiodoInicioConversao[0]));
        String periodoinicio = converteinicio.toString();

        //conversao da data final da pesquisa
        String dataperiodoFim = jtDataFim.getText();
        String[] dataperiodoFimConversao = dataperiodoFim.split("-");
        LocalDate convertefim = LocalDate.of(Integer.parseInt(dataperiodoFimConversao[2]),Integer.parseInt(dataperiodoFimConversao[1]),Integer.parseInt(dataperiodoFimConversao[0]));
        String periodofim = convertefim.toString();
        
        
      
        String dayChange = jtDayChange.getText();
        
        try {      
            
            periodos valores1 = DAO1.contaPeriodoInicio(tipoPermanencia,periodozero,periodozero,bancoPermanencia);
            String periodo1_inicio = valores1.getPermanencia1();
            periodos valores2 = DAO1.contaPeriodoFinal(tipoPermanencia,periodozero,periodo_1_final,bancoPermanencia);
            String periodo1_final = valores2.getPermanencia2();
            
           periodos valores3 = DAO1.contaPeriodoInicio(tipoPermanencia, periodozero, periodo_2_inicio,bancoPermanencia);
           String periodo2_inicio = valores3.getPermanencia1();
           periodos valores4 = DAO1.contaPeriodoFinal(tipoPermanencia, periodozero, periodo_2_final,bancoPermanencia);
           String periodo2_final = valores4.getPermanencia2();
            
           periodos valores5 = DAO1.contaPeriodoInicio(tipoPermanencia, periodozero, periodo_3_inicio,bancoPermanencia);
           String periodo3_inicio = valores5.getPermanencia1();
           periodos valores6 = DAO1.contaPeriodoFinal(tipoPermanencia, periodozero, periodo_3_final,bancoPermanencia);
           String periodo3_final = valores6.getPermanencia2();
          
           periodos valores7 = DAO1.contaPeriodoInicio(tipoPermanencia, periodozero, periodo_4_inicio,bancoPermanencia);
           String periodo4_inicio = valores7.getPermanencia1();
           periodos valores8 = DAO1.contaPeriodoFinal(tipoPermanencia, periodozero, periodo_4_final,bancoPermanencia);
           String periodo4_final = valores8.getPermanencia2();
           
           periodos valores9 = DAO1.contaPeriodoInicio(tipoPermanencia, periodozero, periodo_5_inicio,bancoPermanencia);
           String periodo5_inicio = valores9.getPermanencia1();
           periodos valores10 = DAO1.contaPeriodoFinal(tipoPermanencia, periodozero, periodo_5_final,bancoPermanencia);
           String periodo5_final = valores10.getPermanencia2();
           
           periodos valores11 = DAO1.contaPeriodoInicio(tipoPermanencia, periodozero, periodo_6_inicio,bancoPermanencia);
           String periodo6_inicio = valores11.getPermanencia1();
           periodos valores12 = DAO1.contaPeriodoFinal(tipoPermanencia, periodozero, periodo_6_final,bancoPermanencia);
           String periodo6_final = valores12.getPermanencia2();
           
           periodos valores13 = DAO1.contaPeriodoInicio(tipoPermanencia, periodozero, periodo_7_inicio,bancoPermanencia);
           String periodo7_inicio = valores13.getPermanencia1();
           periodos valores14 = DAO1.contaPeriodoFinal(tipoPermanencia, periodozero, periodo_7_final,bancoPermanencia);
           String periodo7_final = valores14.getPermanencia2();
           
           periodos valores15 = DAO1.contaPeriodoInicio(tipoPermanencia, periodozero, periodo_8_inicio,bancoPermanencia);
           String periodo8_inicio = valores15.getPermanencia1();
           periodos valores16 = DAO1.contaPeriodoFinal(tipoPermanencia, periodozero, periodo_8_final,bancoPermanencia);
           String periodo8_final = valores16.getPermanencia2();
           
           periodos valores17 = DAO1.contaPeriodoInicio(tipoPermanencia, periodozero, periodo_9_inicio,bancoPermanencia);
           String periodo9_inicio = valores17.getPermanencia1();
           periodos valores18 = DAO1.contaPeriodoFinal(tipoPermanencia, periodozero, periodo_9_final,bancoPermanencia);
           String periodo9_final = valores18.getPermanencia2();
             
            periodos valores100 = DAO.Resultado(periodo1_inicio, periodo1_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo1.setText(valores100.getPeriodo1());
            
            periodos valores110 = DAO.Resultado(periodo2_inicio, periodo2_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo2.setText(valores110.getPeriodo1());
            
            periodos valores120 = DAO.Resultado(periodo3_inicio, periodo3_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo3.setText(valores120.getPeriodo1());
            
            periodos valores130 = DAO.Resultado(periodo4_inicio, periodo4_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo4.setText(valores130.getPeriodo1());
            
            periodos valores140 = DAO.Resultado(periodo5_inicio, periodo5_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo5.setText(valores140.getPeriodo1());
            
            periodos valores150 = DAO.Resultado(periodo6_inicio, periodo6_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo6.setText(valores150.getPeriodo1());
            
            periodos valores160 = DAO.Resultado(periodo7_inicio, periodo7_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo7.setText(valores160.getPeriodo1());

            periodos valores170 = DAO.Resultado(periodo8_inicio, periodo8_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo8.setText(valores170.getPeriodo1());
            
            periodos valores180 = DAO.Resultado(periodo9_inicio, periodo9_final, periodoinicio, dayChange,periodofim,bancoPermanencia);
            jtPeriodo9.setText(valores180.getPeriodo1());
            
            int valor1,valor2,valor3,valor4,valor5,valor6,valor7,valor8,valor9,valorTotal;
            
            valor1 = Integer.parseInt(jtPeriodo1.getText());
            valor2 = Integer.parseInt(jtPeriodo2.getText());
            valor3 = Integer.parseInt(jtPeriodo3.getText());
            valor4 = Integer.parseInt(jtPeriodo4.getText());
            valor5 = Integer.parseInt(jtPeriodo5.getText());
            valor6 = Integer.parseInt(jtPeriodo6.getText());
            valor7 = Integer.parseInt(jtPeriodo7.getText());
            valor8 = Integer.parseInt(jtPeriodo8.getText());
            valor9 = Integer.parseInt(jtPeriodo9.getText());
            valorTotal = valor1 +valor2 +valor3 +valor4 +valor5 +valor6 +valor7 +valor8 +valor9;
            
            jtPeriodo10.setText(String.valueOf(valorTotal));
            
            
            JOptionPane.showMessageDialog(null," Consulta realizada com sucesso " );
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Os Periodos não forma atualizados \n"
                    + "- Verificar o periodo pesquisado \n"
                    + "- Verificar o DataBase selecionado ");
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = Integer.parseInt((String) jcSelecaoPeriodo.getSelectedItem());
        String bancoPermanencia = (String) jComboBoxBanco.getSelectedItem(); 
        try {
    
            if(id == 1)
            {
            jtPeriodo1.setText("");
            jtPeriodo2.setText("");
            jtPeriodo3.setText("");
            jtPeriodo4.setText("");
            jtPeriodo5.setText("");
            jtPeriodo6.setText("");
            jtPeriodo7.setText("");
            jtPeriodo8.setText("");
            jtPeriodo9.setText("");
            jtPeriodo10.setText("");
            
            periodos valores = DAO.PesquisarPeriodo(id,bancoPermanencia);
            jtPeriodo_1_Ini.setText(valores.getPeriodo_1_ini());
            jtPeriodo_1_Fim.setText(valores.getPeriodo_1_fim());
            
            jtPeriodo_2_Ini.setText(valores.getPeriodo_2_ini());
            jtPeriodo_2_Fim.setText(valores.getPeriodo_2_fim());
            
            jtPeriodo_3_Ini.setText(valores.getPeriodo_3_ini());
            jtPeriodo_3_Fim.setText(valores.getPeriodo_3_fim());
            
            jtPeriodo_4_Ini.setText(valores.getPeriodo_4_ini());
            jtPeriodo_4_Fim.setText(valores.getPeriodo_4_fim());
            
            jtPeriodo_5_Ini.setText(valores.getPeriodo_5_ini());
            jtPeriodo_5_Fim.setText(valores.getPeriodo_5_fim());
            
            jtPeriodo_6_Ini.setText(valores.getPeriodo_6_ini());
            jtPeriodo_6_Fim.setText(valores.getPeriodo_6_fim());
            
            jtPeriodo_7_Ini.setText(valores.getPeriodo_7_ini());
            jtPeriodo_7_Fim.setText(valores.getPeriodo_7_fim());
            
            jtPeriodo_8_Ini.setText(valores.getPeriodo_8_ini());
            jtPeriodo_8_Fim.setText(valores.getPeriodo_8_fim());
            
            jtPeriodo_9_Ini.setText(valores.getPeriodo_9_ini());
            jtPeriodo_9_Fim.setText(valores.getPeriodo_9_fim());

            JOptionPane.showMessageDialog(null,"Período 1 Selecionado !!");
         
            }
            if(id == 2)
            {
                            jtPeriodo1.setText("");
            jtPeriodo2.setText("");
            jtPeriodo3.setText("");
            jtPeriodo4.setText("");
            jtPeriodo5.setText("");
            jtPeriodo6.setText("");
            jtPeriodo7.setText("");
            jtPeriodo8.setText("");
            jtPeriodo9.setText("");
            jtPeriodo10.setText("");
            
            periodos valores = DAO.PesquisarPeriodo(id,bancoPermanencia);
            jtPeriodo_1_Ini.setText(valores.getPeriodo_1_ini());
            jtPeriodo_1_Fim.setText(valores.getPeriodo_1_fim());
            
            jtPeriodo_2_Ini.setText(valores.getPeriodo_2_ini());
            jtPeriodo_2_Fim.setText(valores.getPeriodo_2_fim());
            
            jtPeriodo_3_Ini.setText(valores.getPeriodo_3_ini());
            jtPeriodo_3_Fim.setText(valores.getPeriodo_3_fim());
            
            jtPeriodo_4_Ini.setText(valores.getPeriodo_4_ini());
            jtPeriodo_4_Fim.setText(valores.getPeriodo_4_fim());
            
            jtPeriodo_5_Ini.setText(valores.getPeriodo_5_ini());
            jtPeriodo_5_Fim.setText(valores.getPeriodo_5_fim());
            
            jtPeriodo_6_Ini.setText(valores.getPeriodo_6_ini());
            jtPeriodo_6_Fim.setText(valores.getPeriodo_6_fim());
            
            jtPeriodo_7_Ini.setText(valores.getPeriodo_7_ini());
            jtPeriodo_7_Fim.setText(valores.getPeriodo_7_fim());
            
            jtPeriodo_9_Ini.setText(valores.getPeriodo_8_ini());
            jtPeriodo_8_Fim.setText(valores.getPeriodo_8_fim());
            
            jtPeriodo_9_Ini.setText(valores.getPeriodo_9_ini());
            jtPeriodo_9_Fim.setText(valores.getPeriodo_9_fim());

                
                JOptionPane.showMessageDialog(null,"Período 2 Selecionado !!"); 
         
            }
            if(id == 3)
            {
            jtPeriodo1.setText("");
            jtPeriodo2.setText("");
            jtPeriodo3.setText("");
            jtPeriodo4.setText("");
            jtPeriodo5.setText("");
            jtPeriodo6.setText("");
            jtPeriodo7.setText("");
            jtPeriodo8.setText("");
            jtPeriodo9.setText("");
            jtPeriodo10.setText("");
            
            periodos valores = DAO.PesquisarPeriodo(id,bancoPermanencia);
            jtPeriodo_1_Ini.setText(valores.getPeriodo_1_ini());
            jtPeriodo_1_Fim.setText(valores.getPeriodo_1_fim());
            
            jtPeriodo_2_Ini.setText(valores.getPeriodo_2_ini());
            jtPeriodo_2_Fim.setText(valores.getPeriodo_2_fim());
            
            jtPeriodo_3_Ini.setText(valores.getPeriodo_3_ini());
            jtPeriodo_3_Fim.setText(valores.getPeriodo_3_fim());
            
            jtPeriodo_4_Ini.setText(valores.getPeriodo_4_ini());
            jtPeriodo_4_Fim.setText(valores.getPeriodo_4_fim());
            
            jtPeriodo_5_Ini.setText(valores.getPeriodo_5_ini());
            jtPeriodo_5_Fim.setText(valores.getPeriodo_5_fim());
            
            jtPeriodo_6_Ini.setText(valores.getPeriodo_6_ini());
            jtPeriodo_6_Fim.setText(valores.getPeriodo_6_fim());
            
            jtPeriodo_7_Ini.setText(valores.getPeriodo_7_ini());
            jtPeriodo_7_Fim.setText(valores.getPeriodo_7_fim());
            
            jtPeriodo_9_Ini.setText(valores.getPeriodo_8_ini());
            jtPeriodo_8_Fim.setText(valores.getPeriodo_8_fim());
            
            jtPeriodo_9_Ini.setText(valores.getPeriodo_9_ini());
            jtPeriodo_9_Fim.setText(valores.getPeriodo_9_fim());

            JOptionPane.showMessageDialog(null,"Período 3 Selecionado !!");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Selecionar período" +ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtPeriodo_1_FimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPeriodo_1_FimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPeriodo_1_FimActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null,"Aplicação encerrada");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String bancoPermanencia = (String) jComboBoxBanco.getSelectedItem(); 
    try{
    spacenet con = new spacenet();
    con.getConexao(bancoPermanencia);
    Statement st = con.dbConn.createStatement();
    ResultSet rs = st.executeQuery("select day_change from configuracao_basica");
        JOptionPane.showMessageDialog(null," Banco de dados "+bancoPermanencia+" conectado");
    while(rs.next())
    {
        jtDayChange.setText(rs.getString("DAY_CHANGE"));
    }
   
    }
    catch(Exception ex )
    {
        JOptionPane.showMessageDialog(null,"Erro de conexao :" +ex.getMessage());
    }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        if(!"".equals(jtPeriodo10.getText()))
        {
//  este metodo realiza a impressão em pdf através da biblioteca itext
        Document documento = new Document();
            
        
        
        try {
            
            PdfWriter.getInstance(documento, new FileOutputStream("C:\\Relatorio_Permanencia\\PERMANENCIA.pdf"));
            documento.open();
            documento.setPageSize(PageSize.A4);
            Image imagem = Image.getInstance("C:\\Relatorio_Permanencia\\logo.jpg");
            imagem.scaleToFit(80,80);
            imagem.setAlignment(Element.PARAGRAPH);
            documento.add(imagem);
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("                   RELATÓRIO DE PERMANENCIA - NEPOS         "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("VIGENCIA DO RELATÓRIO "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("Day Change : " + jtDayChange.getText()));
            documento.add(new Paragraph("Inicio : "+jtDataInicio.getText()));
            documento.add(new Paragraph("Fim   : "+jtDataFim.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("INFORMAÇÕES DO PERIODO PESQUISADO "));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 1                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_1_Ini.getText()+" "+"Até : "+jtPeriodo_1_Fim.getText()+"              "+ jtPeriodo1.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 2                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_2_Ini.getText()+" "+"Até : "+jtPeriodo_2_Fim.getText()+"              "+ jtPeriodo2.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 3                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_3_Ini.getText()+" "+"Até : "+jtPeriodo_3_Fim.getText()+"              "+ jtPeriodo3.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 4                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_4_Ini.getText()+" "+"Até : "+jtPeriodo_4_Fim.getText()+"              "+ jtPeriodo4.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 5                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_5_Ini.getText()+" "+"Até : "+jtPeriodo_5_Fim.getText()+"              "+ jtPeriodo5.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 6                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_6_Ini.getText()+" "+"Até : "+jtPeriodo_6_Fim.getText()+"              "+ jtPeriodo6.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 7                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_7_Ini.getText()+" "+"Até : "+jtPeriodo_7_Fim.getText()+"              "+ jtPeriodo7.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 8                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_8_Ini.getText()+" "+"Até : "+jtPeriodo_8_Fim.getText()+"              "+ jtPeriodo8.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("PERIODO 9                              QUANTIDADE"));
            documento.add(new Paragraph("De : "+jtPeriodo_9_Ini.getText()+" "+"Até : "+jtPeriodo_9_Fim.getText()+"              "+ jtPeriodo9.getText()));
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph("TOTAL DE VEÍCULOS : "+jtPeriodo10.getText()));
            documento.addAuthor("NEPOS - Automação de Estacionamentos");
            documento.addCreationDate();
            JOptionPane.showMessageDialog(null,"Relatório criado com sucesso");
            documento.close();
            int resposta;
            resposta = JOptionPane.showConfirmDialog(null,"Relatório Permanencia","Deseja Abrir o Relatório",JOptionPane.YES_NO_OPTION);
            
            if(resposta == 0)
            {
        String aplicativo = "C:\\Relatorio_Permanencia\\PERMANENCIA.pdf";
        ProcessBuilder P = new ProcessBuilder();
        P.command("cmd.exe","/c",aplicativo);
        P.start();

            }
        } catch 
                
                (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Erro FileNotFound" +ex.getMessage());
        } catch (DocumentException ex) {
            JOptionPane.showMessageDialog(null,"Erro Document " +ex.getMessage());
        } catch (IOException ex) {
            Logger.getLogger(FormPerm.class.getName()).log(Level.SEVERE, null, ex);
        }  
        }
        else
        JOptionPane.showMessageDialog(null,"Realizar a pesquisa para o relatório ser atualizado \n","Processo incorreto", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

       String SQL = "SELECT * FROM PERMANENCIA_ASA";
       String bancoPermanencia = (String) jComboBoxBanco.getSelectedItem();
       resultado relatorio = new resultado();
       relatorio.GeraRelatorio(SQL,bancoPermanencia);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null,"Para alterar os Periodos entrar em contato com a Nepos \n"
                + "Telefone : 3018-5400");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboBoxBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPerm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPerm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPerm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPerm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormPerm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FormPerm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxBanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JComboBox<String> jcSelecaoPeriodo;
    private javax.swing.JFormattedTextField jtDataFim;
    private javax.swing.JFormattedTextField jtDataInicio;
    private javax.swing.JFormattedTextField jtDayChange;
    private javax.swing.JTextField jtPeriodo1;
    private javax.swing.JTextField jtPeriodo10;
    private javax.swing.JTextField jtPeriodo2;
    private javax.swing.JTextField jtPeriodo3;
    private javax.swing.JTextField jtPeriodo4;
    private javax.swing.JTextField jtPeriodo5;
    private javax.swing.JTextField jtPeriodo6;
    private javax.swing.JTextField jtPeriodo7;
    private javax.swing.JTextField jtPeriodo8;
    private javax.swing.JTextField jtPeriodo9;
    private javax.swing.JTextField jtPeriodo_1_Fim;
    private javax.swing.JTextField jtPeriodo_1_Ini;
    private javax.swing.JTextField jtPeriodo_2_Fim;
    private javax.swing.JTextField jtPeriodo_2_Ini;
    private javax.swing.JTextField jtPeriodo_3_Fim;
    private javax.swing.JTextField jtPeriodo_3_Ini;
    private javax.swing.JTextField jtPeriodo_4_Fim;
    private javax.swing.JTextField jtPeriodo_4_Ini;
    private javax.swing.JTextField jtPeriodo_5_Fim;
    private javax.swing.JTextField jtPeriodo_5_Ini;
    private javax.swing.JTextField jtPeriodo_6_Fim;
    private javax.swing.JTextField jtPeriodo_6_Ini;
    private javax.swing.JTextField jtPeriodo_7_Fim;
    private javax.swing.JTextField jtPeriodo_7_Ini;
    private javax.swing.JTextField jtPeriodo_8_Fim;
    private javax.swing.JTextField jtPeriodo_8_Ini;
    private javax.swing.JTextField jtPeriodo_9_Fim;
    private javax.swing.JTextField jtPeriodo_9_Ini;
    // End of variables declaration//GEN-END:variables


public void diretorio() throws IOException
{   
    boolean diretorio = (new File("C:\\Relatorio_Permanencia").mkdir());
    if(!diretorio)
    {
        System.out.println("Pasta do relatório já foi criada");
    }
       
}
public void selectBanco ()
{
     ArrayList<banco> listabanco = new ArrayList<banco>();
         resultado valor = new resultado();
        try {

            listabanco = valor.finAll();
            
  
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Erro de Conexão com o Banco de Dados ! " + ex.getMessage());
        }
        
       for(int i = 0 ; i<listabanco.size(); i ++)
        { banco valorLista = listabanco.get(i);
        
            jComboBoxBanco.addItem(valorLista.getBancoDeDados());
            System.out.println("Valores" + valorLista.getBancoDeDados());
        }
}

public void desativaPeriodo()
{
    jtPeriodo_1_Ini.setEditable(false);
    jtPeriodo_2_Ini.setEditable(false);
    jtPeriodo_3_Ini.setEditable(false);
    jtPeriodo_4_Ini.setEditable(false);
    jtPeriodo_5_Ini.setEditable(false);
    jtPeriodo_6_Ini.setEditable(false);
    jtPeriodo_7_Ini.setEditable(false);
    jtPeriodo_8_Ini.setEditable(false);
    jtPeriodo_9_Ini.setEditable(false);
    jtPeriodo_1_Fim.setEditable(false); 
    jtPeriodo_2_Fim.setEditable(false);
    jtPeriodo_3_Fim.setEditable(false);
    jtPeriodo_4_Fim.setEditable(false);
    jtPeriodo_5_Fim.setEditable(false);
    jtPeriodo_6_Fim.setEditable(false);
    jtPeriodo_7_Fim.setEditable(false);
    jtPeriodo_8_Fim.setEditable(false);
    jtPeriodo_9_Fim.setEditable(false);
    jtPeriodo1.setEditable(false);
    jtPeriodo2.setEditable(false);
    jtPeriodo3.setEditable(false);
    jtPeriodo4.setEditable(false);
    jtPeriodo5.setEditable(false);
    jtPeriodo6.setEditable(false);
    jtPeriodo7.setEditable(false);
    jtPeriodo8.setEditable(false);
    jtPeriodo9.setEditable(false);
    jtPeriodo10.setEditable(false);    
}

}